version: '2'
services:
    albarm-app:
        image: albarm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://albarm-mysql:3306/albarm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    albarm-mysql:
        extends:
            file: mysql.yml
            service: albarm-mysql
